### ISSUE TITLE
[PE-D][Tester C] End time can be before start time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-3/tp#117]
Their UG states under the add command that "Start time should come before end time."
but this is not enforced in the product. I managed to add events that have end times before their start times. E.g. the running event that I added

![image.png](https://raw.githubusercontent.com/linustws/ped/main/files/b383178f-4ff4-4ee8-b4b8-5d2983bcb3cb.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: linustws/ped#1

**Comment by lhy-hoyin** [comment]
The guide stating the requirement means that the user should follow it. It does not mean that checks were in place for the user to explicitly do the opposite.

Anyways, this is a known bug (#95).

Ps. I this seems more like a `.type.FunctionalityBug`.
