### ISSUE TITLE
[PE-D][Tester A] Possible for an event to have end time earlier than start time

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-3/tp#132]
For example, `add n/Eat d/2023-03-31 s/03:00 e/02:00` adds an event from 03:00 to 02:00.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: glozxi/ped#3

**Comment by lhy-hoyin** [comment]
Duplicate issue: known bug #95
