### ISSUE TITLE
[PE-D][Tester A] Undo command has wrong message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-3/tp#135]
When I undo an `add` command, the message says `Retrieved most recent deleted event: Empty string for Undo action now`, when it should say that the added event has been removed.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: glozxi/ped#4

**Comment by lhy-hoyin** [comment]
Duplicate of known bug, see #112 .
