### ISSUE TITLE
[PE-D][Tester B] Long event title not fully displayed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-3/tp#144]
Event title that is too long is not displayed entirely in the GUI. It also causes event date to be cut-off. Users cannot view events with long titles and their dates in entirety.

![Screenshot 2023-03-31 at 2.58.57 PM.png](https://raw.githubusercontent.com/jmestxr/ped/main/files/44c4d0c6-5215-4a93-8c7a-1d12b83c9768.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jmestxr/ped#11

**Comment by lhy-hoyin** [comment]
@AY2223S2-CS2103-W17-3/developers should be set a limit on how long a event title can be?
