### ISSUE TITLE
[PE-D][Tester B] Target user for product not specified clearly in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W17-3/tp#155]
The target user for the product is not specified clearly in the user guide.

![Screenshot 2023-03-31 at 3.18.44 PM.png](https://raw.githubusercontent.com/jmestxr/ped/main/files/4f149f5b-8c2a-4f0b-88d5-552cbe476719.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jmestxr/ped#13

**Comment by lhy-hoyin** [comment]
Same as issue #158
