### ISSUE TITLE
Exception handling for DateTimeParseException

### ISSUE THREAD

**Issue by JrmCkh** [AY2223S2-CS2103-W17-3/tp#175]
DateTimeParseException/InvalidDateException under Date and MainWindow class does not act in the same fashion as ParseException/CommandException from AB3.

1. Error message is displayed to user
2. IDEA still shows the error messages, which ParseException/CommandException from AB3 do not

**Comment by lhy-hoyin** [comment]
Can you give me an example of an invalid date that will cause `InvalidDateException` to be thrown?

**Comment by JrmCkh** [comment]
@lhy-hoyin Example: add n/test d/2024-02-31 s/14:00 e/15:00

**Comment by lhy-hoyin** [comment]
Currently, in MainWindow#executeCommand, `CommandException`, `ParseException`, `InvalidDateException` are caught and log/print error message. Inside the catch clause, `throw e` continues to throw the error to the method which called MainWindow#executeCommand.

In this case, CommandBox#handleCommandEntered is calling MainWindow#executeCommand. Inside the `handleCommandEntered()`, `CommandException` and `ParseException` are caught and and handled (no more throw, so the exception stops here). However, `InvalidDateException` is not caught and handled, thus continues to be throw until its causes 
a `InvocationTargetException`.

To resolve the issue, just simply catch `InvalidDateException` along with the other 2 exceptions in CommandBox.java line 49.
